package com.demo.number.dto;
// default package
// Generated 15 Jan, 2019 11:32:10 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Number generated by hbm2java
 */
@Entity
@Table(name = "Number", catalog = "demodb")
public class Number implements java.io.Serializable {

	private Integer id;
	private Integer number;

	public Number() {
	}

	public Number(Integer number) {
		this.number = number;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
